/** أسماء أحداث التدقيق الموحّدة. */
export const AuditAction = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_REFRESH: 'AUTH_REFRESH',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',
  SUBSCRIPTION_CHANGE: 'SUBSCRIPTION_CHANGE',
  PLAN_EDIT: 'PLAN_EDIT',
  STORE_DELETE: 'STORE_DELETE',
  BOT_CONFIGURE: 'BOT_CONFIGURE',
  BOT_DELETE: 'BOT_DELETE',
  // إجراءات مشرف المنصّة
  ADMIN_USER_SUSPEND: 'ADMIN_USER_SUSPEND',
  ADMIN_USER_ACTIVATE: 'ADMIN_USER_ACTIVATE',
  ADMIN_STORE_SUSPEND: 'ADMIN_STORE_SUSPEND',
  ADMIN_STORE_ACTIVATE: 'ADMIN_STORE_ACTIVATE',
  ADMIN_SUBSCRIPTION_CHANGE: 'ADMIN_SUBSCRIPTION_CHANGE',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
